# Numpy Dot && matmul

In [1]:
import numpy as np

## Dot product
`numpy.dot(a, b, out=None`
- if a and b are 1-D array, it is inner product of vectors
$$dot(a,b) = \sum_{i=0}^n(a[i] * b[i])$$ 
- if a and b are 2-D array, it is matrix multiplication, but using `matmul` or `a @ b` is perferred
$$dot(a,b)[i,j]= matmul(a,b) = a@b = \sum_{k=0}^n(a[i,k] * b[k,j])$$
- if either a or b is scalar, it is multiply, but using `multiply(a,b)` or `a * b` is perferred

- if a is N-D array and b is 1-D array, it is a sum product over the last axis of a and b
$$dot(a,b)[i,j] = \sum_{k=0}^n(a[i, j, k] * b[k])$$ 
$$要求a的最后一维，和b的长度，是一致$$

- if a is N-D array and b is M-D array, it is a sum product over the last axis of a and the second-to-last axis of b
$$dot(a,b)[i, j, k, m] = sum(a[i,j, :] * b[k, :, m])$$
$$要求a的最后一维的维度，和b的倒数第二维的维度，是一致$$

In [2]:
# if a and b are 1-D array, it is inner product of vectors
a = np.array([1, 1, 1])
b = np.array([2, 3, 4])

np.dot(a,b)

9

In [5]:
# if a and b are 2-D array, it is matrix multiplication, but using matmul or a @ b is perferred
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

print(np.dot(a,b))
print(np.matmul(a,b))
print(a @ b)

[[4 1]
 [2 2]]
[[4 1]
 [2 2]]
[[4 1]
 [2 2]]


In [11]:
# if a is N-D array and b is 1-D array, it is a sum product over the last axis of a and b
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,2,3)
b = np.array([1, 1, 1])
print(a, '\n\n', b)
print('\n np.dot(a,b)=\n', np.dot(a, b))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

 [1 1 1]

 np.dot(a,b)=
 [[ 6 15]
 [24 33]]


In [12]:
# if a is N-D array and b is M-D array, it is a sum product over the last axis of a and the second-to-last axis of b
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape(5,4,6,3)

ab = np.dot(a,b)

print(ab.shape)

(3, 4, 5, 5, 4, 3)


In [16]:
print(ab[2,3,2, 1, 2,2])
print(sum(a[2,3,2,:] * b[1, 2, :, 2]))

499128
499128


## Multiply Product, (Element-wise)
`numpy.multiply(X1, X2, out=None, where=True, casting='same_kind'`
- X1, X2, array_like, if X1.shape != X2.shape, they must be broadcastable to a common shape 
- The product of X1 and X2, element-wise, This is a scalar if both X1 and X2 are scalar

In [17]:
X1 = np.array([2, 3])
X2 = np.array([4, 5])
np.multiply(X1, X2)

array([ 8, 15])

In [19]:
X1 = np.arange(9).reshape(3,3)
X2 = np.arange(3)

print("X1=",X1, "\nX2=",X2)

np.multiply(X1, X2)

X1= [[0 1 2]
 [3 4 5]
 [6 7 8]] 
X2= [0 1 2]


array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [ ]:
X1 = np.arange(9).reshape(3,3)
X2 = np.arange(3)

print("X1=",X1, "\nX2=",X2)

np.multiply(X1, X2)

## Matrix Multipy
`numpy.matmul(x1, x2, casting='same_kind`, order='k')`
- The matrix product of the inputs, This is scalar only when both X1, X2 are 1-d vectors
- if x1 and x2 are 2-D array, it is conventional matrices
- if either x1 or x2 is N-D array(N>2), it is treated as a stack of matrices residing in the last two indexes and broadcast according
```
# 所以要求X1最后两维能够和X2的最后两维进行矩阵乘法，同时保证其它的维度可以进行广播
# (9,5,7,4) -> (9,5,7,4) 
# (9,5,4,3) -> (9,5,4,3)
```
- if either x1 or x2 is 1-D array, it is promoted to a matrix by appending a 1 to its dimensions, After matrix multiplication the appended 1 is removed

In [20]:
# if x1 and x2 are 2-D array, it is conventional matrices
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

np.matmul(a,b)


array([[4, 1],
       [2, 2]])

In [21]:
# if either x1 or x2 is 1-D array, it is promoted to a matrix by appending a 1 to its dimensions, After matrix multiplication the appended 1 is removed
a = np.array([[1, 0], [0, 1]])
b = np.array([1, 2])

print(np.matmul(a, b))
print(np.matmul(b, a))

[1 2]
[1 2]


In [24]:
# if either x1 or x2 is N-D array(N>2), it is treated as a stack of matrices residing in the last two indexes and broadcast according
a = np.arange(9*5*7*4).reshape((9,5,7,4))
b = np.arange(8*6*4*3).reshape((8,6,4,3))

abdot = np.dot(a,b)
print('abdot.shape=', abdot.shape)

abmat = np.matmul(a,b)
print('abmat.shape=', abmat.shape)

abdot.shape= (9, 5, 7, 8, 6, 3)


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (9,5,7,4)->(9,5,7,newaxis,4) (8,6,4,3)->(8,6,newaxis,3,4) 

In [28]:
a = np.arange(8*9*5*7*4).reshape((8,9,5,7,4))
b = np.arange(9*5*4*3).reshape((9,5,4,3))

abdot = np.dot(a,b)
print('abdot.shape=', abdot.shape)

# 所以要求X1最后两维能够和X2的最后两维进行矩阵乘法，同时保证其它的维度可以进行广播
# (9,5,7,4) -> (9,5,7,4) 
# (9,5,4,3) -> (9,5,4,3)
abmat = np.matmul(a,b)
print('abmat.shape=', abmat.shape)
# 

abdot.shape= (8, 9, 5, 7, 9, 5, 3)
abmat.shape= (8, 9, 5, 7, 3)
