# Solving Linear Systems

## Linear algebra（numpy.linalg）
The NumPy linear algebra function rely on BLAS and LAPACK to provide efficient low level implementations of standard linear algebra algorithms. Those libraries may be provided by NumPy itself using C versions of a subset of their reference implementations.

### Matrix and vector products
- dot(a, b)
- linalg.multi_dot
- vdot(a, b)
- inner(a, b)
- matmul(x1, x2)
- tensordot(a, b)

## Decompositions
- linalg.cholesky(a)     Cholesky Decompositions
- linalg.qr(a)           Compute the qr factorization of a matrix 
- linalg.svd(a)          Sigular Value Decomposition 

## Matrix eigenvalues
- linalg.eig(a)          Compute the eigenvalues and right eigenvectors of a square array
- linalg.eigh(a)         Compute the eigenvalues and eigenvectors of a complex Hermitian or a real symmetrix matrix 
- linalg.eigvals(a)      Compute the eigenvalues of a general matrix 
- linalg.eigvalsh(a)     Compute the eigenvaluse of a complex Hermitian or real symmetric matrix 

## Norms and other numbers
- linalg.norm(x)         matrix or vector norm
- linalg.cond(x)         conditional number of a matrix 
- linalg.det(a)          determinant of a array
- linalg.matrix_rank(x)  matrix rank of array using SVD method
- linalg.slogdet(a)      
- trace(a)

## Sovling equations and inverting matrice
- linalg.solve(a, b)     solve a linear matrix equation 
- linalg.tensorsolve(a, b) solve the tensor equation `ax=b` for x
- linalg.lstsq(a, b)     the least-squares solution to a linear matrix equation
- linalg.inv(a)          inverse of a matrix 
- linalg.pinv(a)
- linalg.tensorinv(a)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

%matplotlib inline

## Linear Systems
- A linear system of equations is a collectiion of linear equations
https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/


$$
\begin{align}
a_{0,0}x_0 + a_{0,1}x_1 + \cdots + a_{0,n}x_n  = b_0  \\
a_{1,0}x_0 + a_{1,1}x_1 + \cdots + a_{1,n}x_n  = b_1  \\ 
\vdots  \\ 
a_{m,0}x_0 + a_{m,1}x_1 + \cdots + a_{m,n}x_n  = b_m  \\ 
\end{align}
$$

In matrix notation, a linear system is $$Ax = b$$ where
$$
A = \begin{pmatrix}
a_{0,0} & a_{0,1} &  \cdots & a_{0,n} \\
a_{1,0} & a_{1,1} &  \cdots & a_{1,n} \\ 
\vdots  & \vdots  &  \vdots & \vdots  \\ 
a_{m,0} & a_{m,1} &  \cdots & a_{m,n} \\ 
\end{pmatrix},

x = \begin{pmatrix} x_0 \\ x_1 \\ \vdots \\ x_n  \end{pmatrix},
b = \begin{pmatrix} b_0 \\ b_1 \\ \vdots \\ b_m  \end{pmatrix},
$$

for example:
$$
A = \begin{pmatrix} 6 & 15 & 1 \\ 8 & 7 & 12 \\ 2 & 7 & 8 \end{pmatrix}, 
b = \begin{pmatrix} 2 \\ 14 \\ 10 \end{pmatrix}
$$

$$Ax=b$$   $$x=A^{-1}b$$


In [6]:
A = np.array([[6, 15, 1], [8, 7, 12], [2, 7, 8]])
b = np.array([[2], [14], [10]])

print(A, '\n\n', b)

[[ 6 15  1]
 [ 8  7 12]
 [ 2  7  8]] 

 [[ 2]
 [14]
 [10]]


In [8]:
# solution 1 
AT = np.linalg.inv(A)
print('AT=', AT)

x = np.matmul(AT, b)
print('x=', x)


AT= [[ 0.03856749  0.15564738 -0.23829201]
 [ 0.05509642 -0.06336088  0.08815427]
 [-0.05785124  0.01652893  0.10743802]]
x= [[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]


In [9]:
# solution 2 
x = np.linalg.solve(A, b)
print('x=', x)

x= [[-0.12672176]
 [ 0.1046832 ]
 [ 1.19008264]]



## Inverse or Solve
- It's a bad idea to use the inverse $A^{-1}$ to solve $A \mathbf{x} = \mathbf{b}$ if $A$ is large. 
- It's too computationally expensive. 
- Let's create a large random matrix $A$ and vector $\mathbf{b}$ and compute the solution $\mathbf{x}$ in 2 ways:

In [10]:

N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

In [11]:

%%timeit
x = np.linalg.solve(A,b)

30.8 ms ± 9.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%%timeit
x = np.linalg.inv(A) @ b

107 ms ± 23.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
